language: node_js
node_js:
    - "4"
    - "5"
    - "6"

addons:
    code_climate:
        repo_token: e74c5a1fd7e1e991f69073a10b225804bc94ba08787ce00727a8319aa45b5b47

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info